# Generated by Django 5.2.4 on 2025-07-07 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.IntegerField(default=1)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Asset Categories",
            },
        ),
        migrations.CreateModel(
            name="AssetFeature",
            fields=[
                ("feature_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "feature_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "feature_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "feature_desc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.IntegerField(default=1)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Asset Features",
            },
        ),
        migrations.CreateModel(
            name="AssetLocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "address_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "address_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "address_value2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "address_value3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "street_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.IntegerField(default=1)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Asset Locations",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("asset_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "asset_name",
                    models.CharField(
                        blank=True,
                        help_text="Computer name from Excel",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "asset_make",
                    models.CharField(
                        blank=True,
                        help_text="Server make from Excel",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("purchase_id", models.IntegerField(blank=True, null=True)),
                (
                    "asset_type",
                    models.CharField(
                        blank=True,
                        help_text="Type from Excel",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("usage_id", models.IntegerField(blank=True, null=True)),
                (
                    "asset_purpose",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.IntegerField(default=1)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_assets",
                        to="assets.asset",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="assets.assetcategory",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="assets.assetfeature",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="assets.assetlocation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Assets",
            },
        ),
        migrations.CreateModel(
            name="AssetNetworkAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[("IP_ADDRESS", "IP Address"), ("MAC_ID", "MAC ID")],
                        max_length=20,
                    ),
                ),
                ("address_value", models.CharField(max_length=100)),
                ("is_active", models.IntegerField(default=1)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_addresses",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Asset Network Addresses",
                "unique_together": {("asset", "address_type", "address_value")},
            },
        ),
    ]
