# Generated by Django 5.2.4 on 2025-07-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = []
