# Generated by Django 5.2.4 on 2025-07-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = []
